# Generated by Django 6.0.3 on 2026-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furvedaapp', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_5',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
