# Generated by Django 6.0.3 on 2026-04-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furvedaapp', '0006_product_image_url_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBotanical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='botanicals/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botanicals', to='Furvedaapp.product')),
            ],
        ),
    ]
