# Generated by Django 6.0.3 on 2026-04-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Furvedaapp', '0007_productbotanical'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='Furvedaapp.product'),
        ),
    ]
