# Generated by Django 6.0.3 on 2026-04-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furvedaapp', '0008_product_related_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
